ALTER TABLE staff ADD COLUMN IF NOT EXISTS mfa_code VARCHAR(10) DEFAULT NULL;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS mfa_code_expires TIMESTAMP NULL DEFAULT NULL;


ALTER TABLE login_history 
  MODIFY COLUMN result ENUM('SUCCESS','FAILURE','LOCKED','MFA_CHALLENGE','MFA_FAILURE') 
  DEFAULT 'SUCCESS';